language: python
sudo: false
cache:
  pip: true
  timeout: 1000
  directories:
  - $HOME/buildout-cache
python:
  - 2.7
matrix:
  fast_finish: true
install:
  - python bootstrap-buildout.py
  - bin/buildout -N buildout:eggs-directory=$HOME/buildout-cache/eggs buildout:download-cache=$HOME/buildout-cache/downloads
script:
  - bin/test
after_success:
  - bin/createcoverage
  - pip install coverage==3.7 coveralls
  - coveralls
notifications:
  email:
    - pilar.marinas@upcnet.es
