language: python
sudo: false
cache:
  directories:
  - eggs
  - downloads
python:
  - 2.7
matrix:
  fast_finish: true
install:
  - python bootstrap-buildout.py
  - bin/buildout -N buildout:download-cache=downloads annotate
  - bin/buildout -N buildout:download-cache=downloads
  - pip install -U tox coveralls
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- firefox -v
script:
  - bin/test
  - travis_wait 30 tox --develop
after_success:
  - bin/createcoverage
  - coveralls
notifications:
  email:
    - pilar.marinas@upcnet.es
