language: python
sudo: false
cache:
  pip: true
  directories:
  - eggs
  - downloads
python:
  - 2.7
matrix:
  fast_finish: true
install:
  - python bootstrap-buildout.py
  - bin/buildout -N buildout:download-cache=downloads annotate
  - bin/buildout -N buildout:download-cache=downloads
script:
  - bin/test
after_success:
  - bin/createcoverage
  - pip install coveralls
  - coveralls
notifications:
  email:
    - pilar.marinas@upcnet.es
